version: "2"

services:
  nsxv3-exporter:
    tty: true
    stdin_open: true
    expose:
      - 9191
    ports:
      - 9191:9191
    image: nsx-exporter:latest 
    environment:
      - NSXV3_LOGIN_HOST=nsx-floatin-ip.corp.local
      - NSXV3_LOGIN_PORT=443
      - NSXV3_LOGIN_USER=admin
      - NSXV3_LOGIN_PASSWORD=VMwarensbu_1
      - NSXV3_REQUESTS_PER_SECOND=<NSX-T Manager Node requestes per second [<100]>
      - NSXV3_CONNECTION_POOL_SIZE=<NSX-T Manager Node connection pool size>
      - NSXV3_REQUEST_TIMEOUT_SECONDS=<NSX-T Manager request timeout in seconds>
      - NSXV3_SUPPRESS_SSL_WARNINGS=true
      - SCRAP_PORT=9191
      - SCRAP_SCHEDULE_SECONDS=<The exporter scrap NSX-T Manager schedule in seconds>
      - LOG_LEVEL=<NSX-T Exporter logging level.>


